export const FETCH_POST_LIST_DATA =
  "HACKER_NEWS/POST_LIST/FETCH_POST_LIST_DATA";
export const FETCH_POST_LIST_DATA_SUCCESS =
  "HACKER_NEWS/POST_LIST/FETCH_POST_LIST_DATA_SUCCESS";
export const FETCH_POST_LIST_DATA_ERROR =
  "HACKER_NEWS/POST_LIST/FETCH_POST_LIST_DATA_ERROR";
